package Excepions;

import java.util.Scanner;

public class Exception2 {
public static void main(String[] args) {
        try {
		Scanner scan = new Scanner(System.in);
		System.out.println("enter the first number to divide");
		int a = scan.nextInt();
		System.out.println("enter the next number");
		int b = scan.nextInt();
		int res = a / b;
		System.out.println("The result is " + res);
		System.out.println("please enter the size of an Array");
		int size =scan.nextInt();
		int arr[] =new int[size];
		System.out.println("please enter the element of an Array");
		int elem =scan.nextInt();
		System.out.println("Enter the position at which "
				+ "element has to be inserted");
		int pos =scan.nextInt();
		arr[pos]=elem;	
		
        }
        
        catch(ArithmeticException e) {
        	System.out.println("Please enter proper second number");
        }
        catch(NegativeArraySizeException e) {
        	System.out.println("Please enter non-negative number for an array Size");
        }
        catch(ArrayIndexOutOfBoundsException e) {
        	System.out.println("Please be in your Limit");
        }
        System.out.println("Thanks for using application");
	
}
}
